# Generated by Django 4.0.6 on 2022-07-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='bodytext',
            field=models.TextField(blank=True, default='this is by-default'),
        ),
    ]
