# Generated by Django 4.0.6 on 2022-07-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_bodytext'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='permalink',
            field=models.CharField(default='/', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
