# Generated by Django 4.0.6 on 2022-07-24 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='myapp/static/images')),
                ('blogtext', models.TextField(max_length=1000)),
                ('uploadtime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
