# Generated by Django 4.0.6 on 2022-07-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_userdata_choise_userdata_imagename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='imagename',
            field=models.CharField(blank=True, default='images/', max_length=100),
        ),
    ]
