# Generated by Django 4.0.6 on 2022-07-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_profile_profileimage_profile_profileimagename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimage',
            field=models.ImageField(blank=True, upload_to='profileimage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimagename',
            field=models.CharField(blank=True, default='profileimage/', max_length=100),
        ),
    ]
